### ISSUE TITLE
Add Rating System

### ISSUE THREAD

**Issue by Opiskull** [Opiskull/one4all#18]
Add a simple rating system like 10 points or 5 stars

**Comment by honigmacherin** [comment]
Auch haben will :dancers:

**Comment by chrila** [comment]
+1 for 5 stars!

**Comment by Opiskull** [comment]
The stars will be replaced with nuts. This is the peerzone way ;)

**Comment by Opiskull** [comment]
close 0d97e8af3ca042022787862ba99d88ecc1f97995
