### ISSUE TITLE
"Hinzufügen" in neuem Fenster

### ISSUE THREAD

**Issue by honigmacherin** [Opiskull/one4all#20]
Etwas unübersichtlich da unten
Besser
1. Add
2. Fenster öffnet
3. Daten können hinzugefügt, gesucht werden
4. Erst mit Speichern oder Verwerfen, schließt das Fenster wieder.

**Comment by Opiskull** [comment]
Wie hast du dir das vorgstellt mit dem hinzufügen suchen? 
Alles in einem Fenster oder beim suchen dann wieder den jetzigen dialog öffnen?

Edit dann auch in einem eigenen Fenster?

**Comment by Opiskull** [comment]
closed in 287d3b3808dd0aba14b33f8b4dec22b3b7cc743a, 3a14d6b96bc8b726ff07ab533fe1b37fb9d61540
