### ISSUE TITLE
Well-defined status for entries

### ISSUE THREAD

**Issue by chrila** [Opiskull/one4all#29]
Every entry should have a well-defined status, for example one of the following:
{ 'in progress', 'paused', 'finished', 'dropped' }

In UI, there are already status toggle buttons available, just add one with a play icon for 'in progress' or whatever it should be called.

When adding a new entry, it should have a default status which may be configurable by the user in some later version (maybe create a separate issue when the time has come...)

**Comment by Opiskull** [comment]
- MongoDB Migration of old data
- Client: some parts depend heavily on the available bool variables

**Comment by Opiskull** [comment]
@therealko 
@Spitfire0001 
@chrila 

Needs to be discussed!!!

**Comment by chrila** [comment]
What do you think about my suggestion of having 4 possible statuses?
- **in progress**: currently watching (/reading/listening whatever)
- **paused**: not watching, temporarily dropped, waiting for next season,...
- **finished**: nothing more to watch ;)
- **dropped**: stopped watching because e.g. it sucks

Feel free to comment!

**Comment by Opiskull** [comment]
How about to ad another state like
- **not yet started:** to indicate that no status has been assigned

For the other states i totally agree on having them

**Comment by Spitfire0001** [comment]
In my opinion in the in progress state makes only sence for games and books.

In practice you will never set a episode of a series or a movie in progress.

Gesendet von Windows Mail

Von: Christian Lampl
Gesendet: ‎Dienstag‎, ‎26‎. ‎August‎ ‎2014 ‎12‎:‎36
An: Opiskull/14all
Cc: Michal Horvath

What do you think about my suggestion of having 4 possible statuses?
in progress: currently watching (/reading/listening whatever)
paused: not watching, temporarily dropped, waiting for next season,...
finished: nothing more to watch ;)
dropped: stopped watching because e.g. it sucks

Feel free to comment!

**Comment by chrila** [comment]
I don't mean it as for an episode, but for a series in general. And not even in realtime! I set the shows which I am interested in at the time (which are usually 3-4) to 'in progress'. If decide to watch an episode, I just open peerzone, filter for 'in progress' and choose one!

**Comment by therealko** [comment]
[anmine/manga..] "in progress" for a season or the title, but not for every single episode.

example:
today you can watch 3 episodes today and on next day another one => season/titel is in progress.
but if you watch another anime instead of the next episodes, so its "paused"

**Comment by chrila** [comment]
I mean that you can have more than one title in progress! So I don't see it as "watching right now in that moment" but rather as "it's on my watch list at the moment and I watch episodes from time to time".

What do you guys think about that?

**Comment by Opiskull** [comment]
How about ah additional field like currently watching? So it's not a state its another property?

**Comment by Opiskull** [comment]
So... I added a watching state... it's something like ah in progress. The color is purple.
