### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by chrila** [Opiskull/one4all#32]
I think it would be a great improvement if one could **tag** entries with custom tags/labels. For example, someone might want to tag movies as "creepy", "boring", "hot", "contains boobs" etc.

Furthermore it should also be possible to search/filter by tags!

**Comment by Opiskull** [comment]
How about this library?

http://mbenford.github.io/ngTagsInput/

**Comment by Opiskull** [comment]
How the fuck should I display a tag??

**Comment by Opiskull** [comment]
I will close this issue and create another with only search and filter of tags

#43
